# Stranger Theme: Tigers for Alacritty
# https://github.com/stranger-theme/alacritty

[colors.primary]
background = "#181E18"
foreground = "#F5F5F5"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#181E18"
cursor = "#F5F5F5"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#283228"

[colors.normal]
black = "#181E18"
red = "#CC6666"
green = "#B5BD68"
yellow = "#F0C674"
blue = "#B294BB"
magenta = "#FF7F2A"
cyan = "#81A2BE"
white = "#F5F5F5"

[colors.bright]
black = "#5C6C5C"
red = "#EA8484"
green = "#D3DB86"
yellow = "#FFE492"
blue = "#D0B2D9"
magenta = "#FF9D48"
cyan = "#9FC0DC"
white = "#FFFFFF"

[colors.search.matches]
foreground = "#283228"
background = "#B5BD68"

[colors.search.focused_match]
foreground = "#283228"
background = "#DE935F"

[colors.footer_bar]
background = "#181E18"
foreground = "#F5F5F5"

[colors.hints.start]
foreground = "#181E18"
background = "#F0C674"

[colors.hints.end]
foreground = "#F0C674"
background = "#181E18"
